### ISSUE TITLE
Variation select and a lot functions with variable products dont work or miss features 

### ISSUE THREAD

**Issue by DarylDesign** [Crocoblock/jet-woo-widgets#10]
Please add features. Today's eCommerce world is centered around variable products and it has to look good.

Problems and missing features example:

- Variation selection cant be centered
- Variation selection name cant be centered / should be entirely separated from selection or always as one part / on of button would also be great
- Variation clear cant be centered
- Variation pricing design cant be edited right or maybe just doesn't work
- responsive doesn't work right
- product images cant be centered
- other ( there could be many things listed about the variable product styles but these are the most painful.

**Comment by UraraReika** [comment]
Hello @DarylDesign !

If you use full version of JetWooBuilder plugin please post your issue request [here](https://github.com/Crocoblock/suggestions/issues) so we could deal with it more efficiently. Although please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. 

Thank you for your understanding.
