### ISSUE TITLE
Jet woo builder bug

### ISSUE THREAD

**Issue by paulpsky** [Crocoblock/jet-woo-widgets#2]
Jet woo builder will show woocommerce default additional note field in checkout page. However, when filled in will not show with any of the jets woo thank you order widgets and will not push data to email templates or to the order form.

This will happen if jet woo is not used. I know you don't guarantee part integration but surely a jet woo product built for designing woo commerce pages would have compatibility with the 'additional default woo field'

**Comment by UraraReika** [comment]
Hello!
Please leave your request in [proper place](https://github.com/Crocoblock/suggestions/issues)!
