### ISSUE TITLE
JetWooBuilder Template Settings in every product - Not Fine

### ISSUE THREAD

**Issue by enricgomez** [Crocoblock/jet-woo-widgets#5]
My template type by default is Full Width. All my products are set by default and the visibility is not getting full width, just the content.
How it should be:
<img width="1438" alt="Captura de pantalla 2021-08-18 a las 11 36 22" src="https://user-images.githubusercontent.com/15028929/129876974-56e38c91-2fca-4991-817b-01a354891075.png">
How it is wrongly:
<img width="1438" alt="Captura de pantalla 2021-08-18 a las 11 36 37" src="https://user-images.githubusercontent.com/15028929/129877034-ad6efce5-20fd-4ef5-aee2-623381dc1c0c.png">

I have to go product by product and set manually Full Width.

**Comment by enricgomez** [comment]
<img width="339" alt="Captura de pantalla 2021-08-18 a las 11 34 42" src="https://user-images.githubusercontent.com/15028929/129877359-5288a390-ddc1-4bcd-a19b-2fe545345d4e.png">

**Comment by UraraReika** [comment]
Hello!
Please leave your request in [proper place](https://github.com/Crocoblock/suggestions/issues)!
