### ISSUE TITLE
Server request process time

### ISSUE THREAD

**Issue by diogui** [Crocoblock/jet-woo-widgets#6]
Hi, i’ve been using JetWooBuilder locally but now that my site is ready i’ve moved to production and for my surprise the Server Response time of a page with a Product Grid with 12 products paginated takes 1.5 seconds to render. I thought maybe is just me, so I search in crocoblock and thr demo page showing product grid example, takes around 2 seconds to load the page, to answer the request. This is too high loading time speciall on mobile. Any solution for this ?

**Comment by UraraReika** [comment]
Hello @diogui !

If you use full version of JetWooBuilder plugin please post your issue request [here](https://github.com/Crocoblock/suggestions/issues) so we could deal with it more efficiently.

But overall we try our best to optimise our plugins, you can also track this issue https://github.com/Crocoblock/suggestions/issues/2282.

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. If you still need help with this issue or have any other questions about the WooCommerce plugin, please start a new thread.
