### ISSUE TITLE
Endpoint Customisations Missing.

### ISSUE THREAD

**Issue by AndyMorley** [Crocoblock/jet-woo-widgets#7]
I Am using your Woo Page Builder but cant find where to set up or create a **"Lost Password"** endpoint template. IS there any documentation which describes specifically how to do this please, i've been through your End Points tutorial but its not in there.

Ive also spoken to customer services who have informed me that this isnt possible as of yet.

I'm surprised this one was missed when the other end points were done.

There is also the endpoint template customisation for **"Payment Card"** which i cant seem to customise either.

**Comment by UraraReika** [comment]
Hello @AndyMorley !

You use full version of JetWooBuilder plugin so please post your issue request [here](https://github.com/Crocoblock/suggestions/issues) so we could deal with it more efficiently.

But there is already created issues with such problem so please track them https://github.com/Crocoblock/suggestions/issues/2721.
