### ISSUE TITLE
Crocoblock cart popup not appearing for mobile on only books demo and wizard files broken.

### ISSUE THREAD

**Issue by mrgithub** [Crocoblock/jet-woo-widgets#8]
I used the wizard to install  only books demo using recommended plugins and hello theme. I love it but its sloppy in parts.

The cart does not have the same behaviour as desktop - it goes straight to checkout when clicked. No popup appears and it doesnt go to the cart page only to checkout.

Also the hidden search icon that appears only for mobile is badly misaligned. I've spent days trying to align it so its more responsive.  On the crocoblocks demo site this is aligned - so wizard files are not the same.

Please update your wizard demo files and check they work for mobile against hello theme.

**Comment by UraraReika** [comment]
Hello @mrgithub !

This problem connected to Crocoblock overall so please post your issue request [here](https://github.com/Crocoblock/suggestions/issues) so we could deal with it more efficiently. We although have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!
