### ISSUE TITLE
dynamic background color on any kind of product loop

### ISSUE THREAD

**Issue by waazaa** [Crocoblock/jet-woo-widgets#9]
Please check this: I add a color picker metabox with jet engine and display correctly in the product loop image background custom template but on releated products (and probably the other kinds of loops like up/cross sells) it doesn't...it's display like this:
[image](https://imgur.com/a/2nW9cQg)
hope you can fix it
cheers

**Comment by UraraReika** [comment]
Hello @diogui !

If you use full version of JetWooBuilder plugin please post your issue request [here](https://github.com/Crocoblock/suggestions/issues) so we could deal with it more efficiently. Although we have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. 

Thank you!
